plt.plot(history.history['loss'],color='green',label='Training Loss')
plt.plot(history.history['val_loss'],color='blue',label='Validation loss')
plt.legend(loc='upper right')
plt.title('Loss variation')
plt.savefig('Model Training History')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.show()
plt.plot(history.history['accuracy'], color = 'green', label = 'accuracy')
plt.plot(history.history['val_accuracy'], color = 'blue', label = 'val_accuracy')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.title('Accuracy')
plt.legend(loc = 'upper right')
plt.show()
